apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

bases:
  - ../base

namePrefix: app-

patches:
  - patch: |
      - op: replace
        path: /spec/running
        value: true
      - op: replace
        path: /spec/template/spec/domain/memory/guest
        value: 2Gi
      - op: replace
        path: /spec/template/spec/volumes/1/cloudInitNoCloud/userData
        value: |-
          #cloud-config
          user: fedora
          password: fedora123
          chpasswd: { expire: False }
      - op: replace
        path: /spec/dataVolumeTemplates/0/metadata/name
        value: dv-app
      - op: replace
        path: /spec/template/spec/volumes/0/dataVolume/name
        value: dv-app
    target:
      kind: VirtualMachine
