apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: vms
spec:
  generators:
  - clusters: {}
  - list:
      elements:
      - appName: vm1
        gitPath: dev
        namespace: ns-vm
        dataVolumeName: dev-datavolume
      - appName: vm2
        gitPath: prod
        namespace: ns-vm
        dataVolumeName: prod-datavolume
  template:
    metadata:
      name: "{{appName}}"
    spec:
      project: default
      source:
        repoURL: https://github.com/sen31088/vm-deployment.git
        targetRevision: HEAD
        path: "applicationsets/vm/kustomize/{{gitPath}}"
      destination:
        name: in-cluster
        namespace: "{{namespace}}"
      syncPolicy:
        syncOptions:
        - CreateNamespace=true
        automated:
          selfHeal: true
          prune: true
