apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: vms
spec:
  generators:
    - git:
        repoURL: https://github.com/sen31088/vm-deployment.git
        revision: HEAD
        directories:
          - path: applicationsets/vm/kustomize/*
  template:
    metadata:
      name: "{{appName}}"
    spec:
      project: default
      source:
        repoURL: https://github.com/sen31088/vm-deployment.git
        targetRevision: HEAD
        path: "applicationsets/vm/kustomize/{{gitPath}}"
      destination:
        name: in-cluster
        namespace: "{{namespace}}"
      syncPolicy:
        syncOptions:
          - CreateNamespace=true
        automated:
          selfHeal: true
          prune: true
