apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: vms
spec:
  generators:
    - clusters: {}
    - list:
        elements:
          - appName: web
            gitPath: web
            namespace: ns-vm
          - appName: app
            gitPath: app
            namespace: ns-vm
          - appName: app1
            gitPath: app1
            namespace: ns-vm
          - appName: db
            gitPath: db
            namespace: ns-vm
  template:
    metadata:
      name: "{{appName}}"
    spec:
      project: default
      source:
        repoURL: https://github.com/sen31088/vm-deployment.git
        targetRevision: HEAD
        path: "applicationsets/vm/kustomize/{{gitPath}}"
      destination:
        name: in-cluster
        namespace: "{{namespace}}"
      syncPolicy:
        syncOptions:
          - CreateNamespace=true
        automated:
          selfHeal: true
          prune: true
